import type { PoolClient } from 'pg';
import db from '../config/db';
import type {
  Layer,
  LayerRow,
  InsertLayerInput,
  UpdateLayerParentInput,
  UpdateLayerRestrictedInput,
} from '../models/layer';
import { rowToLayer } from '../models/layer';

// ─── helpers ──────────────────────────────────────────────────────────────────

/**
 * Maps a raw pg result row to the camelCase `Layer` model.
 * Centralised here so all queries go through the same transform.
 */
function toLayer(row: LayerRow): Layer {
  return rowToLayer(row);
}

// ─── LayerRepository ─────────────────────────────────────────────────────────

/**
 * Raw `pg` data-access layer for the `layer_registry` table.
 *
 * Rules:
 * - No business logic lives here — only SQL + row mapping.
 * - Every method accepts an optional `PoolClient` so it can participate
 *   in a caller-managed transaction when needed.
 * - All queries use parameterised `$1, $2 …` placeholders.
 */
export const LayerRepository = {
  // ── getAllLayers ───────────────────────────────────────────────────────────

  /**
   * Returns every row in `layer_registry`, ordered by creation date.
   * The caller (service layer) is responsible for building the tree.
   */
  async getAllLayers(client?: PoolClient): Promise<Layer[]> {
    const query = `
      SELECT
        id,
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible,
        created_at,
        updated_at
      FROM layer_registry
      ORDER BY created_at ASC
    `;
    const conn   = client ?? db;
    const result = await conn.query<LayerRow>(query);
    return result.rows.map(toLayer);
  },

  // ── findByGeoserverName ────────────────────────────────────────────────────

  /**
   * Returns a single layer matching the exact GeoServer layer name,
   * or `null` if not found.
   */
  async findByGeoserverName(
    geoserverName: string,
    client?: PoolClient,
  ): Promise<Layer | null> {
    const query = `
      SELECT
        id,
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible,
        created_at,
        updated_at
      FROM layer_registry
      WHERE geoserver_name = $1
      LIMIT 1
    `;
    const conn   = client ?? db;
    const result = await conn.query<LayerRow>(query, [geoserverName]);
    return result.rows.length > 0 ? toLayer(result.rows[0]!) : null;
  },

  // ── findById ──────────────────────────────────────────────────────────────

  /**
   * Returns a single layer matching the UUID, or `null` if not found.
   */
  async findById(id: string, client?: PoolClient): Promise<Layer | null> {
    const query = `
      SELECT
        id,
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible,
        created_at,
        updated_at
      FROM layer_registry
      WHERE id = $1
      LIMIT 1
    `;
    const conn   = client ?? db;
    const result = await conn.query<LayerRow>(query, [id]);
    return result.rows.length > 0 ? toLayer(result.rows[0]!) : null;
  },

  // ── insertLayer ───────────────────────────────────────────────────────────

  /**
   * Inserts a new layer and returns the full persisted record.
   * UUID is generated by the database (`gen_random_uuid()`).
   */
  async insertLayer(
    input: InsertLayerInput,
    client?: PoolClient,
  ): Promise<Layer> {
    const query = `
      INSERT INTO layer_registry (
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible
      )
      VALUES ($1, $2, $3, $4, $5)
      RETURNING
        id,
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible,
        created_at,
        updated_at
    `;
    const params = [
      input.name,
      input.geoserverName,
      input.parentId   ?? null,
      input.restricted ?? false,
      input.visible    ?? true,
    ];
    const conn   = client ?? db;
    const result = await conn.query<LayerRow>(query, params);
    return toLayer(result.rows[0]!);
  },

  // ── updateLayerParent ─────────────────────────────────────────────────────

  /**
   * Reassigns the parent of a layer.
   * Pass `parentId: null` to promote a layer to root level.
   * Returns the updated record or `null` if the id was not found.
   */
  async updateLayerParent(
    input: UpdateLayerParentInput,
    client?: PoolClient,
  ): Promise<Layer | null> {
    const query = `
      UPDATE layer_registry
      SET
        parent_id  = $1,
        updated_at = NOW()
      WHERE id = $2
      RETURNING
        id,
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible,
        created_at,
        updated_at
    `;
    const conn   = client ?? db;
    const result = await conn.query<LayerRow>(query, [input.parentId, input.id]);
    return result.rows.length > 0 ? toLayer(result.rows[0]!) : null;
  },

  // ── updateRestricted ──────────────────────────────────────────────────────

  /**
   * Toggles / sets the `restricted` access flag on a layer.
   * Returns the updated record or `null` if the id was not found.
   */
  async updateRestricted(
    input: UpdateLayerRestrictedInput,
    client?: PoolClient,
  ): Promise<Layer | null> {
    const query = `
      UPDATE layer_registry
      SET
        restricted = $1,
        updated_at = NOW()
      WHERE id = $2
      RETURNING
        id,
        name,
        geoserver_name,
        parent_id,
        restricted,
        visible,
        created_at,
        updated_at
    `;
    const conn   = client ?? db;
    const result = await conn.query<LayerRow>(query, [input.restricted, input.id]);
    return result.rows.length > 0 ? toLayer(result.rows[0]!) : null;
  },

  // ── deleteLayer ───────────────────────────────────────────────────────────

  /**
   * Hard-deletes a layer.  Children are also deleted via ON DELETE CASCADE.
   * Returns `true` if a row was deleted, `false` if the id was not found.
   */
  async deleteLayer(id: string, client?: PoolClient): Promise<boolean> {
    const query = `DELETE FROM layer_registry WHERE id = $1`;
    const conn   = client ?? db;
    const result = await conn.query(query, [id]);
    return (result.rowCount ?? 0) > 0;
  },
};
